### PR TITLE
Upgrade VS Code Camel to 0.0.21 eclipse/che#19123

### PR DESCRIPTION
**Pull request by apupier**
the Camel K binary used by default is newer (upgrade to 1.3.1)

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by apupier** [comment]
@ericwill  there is still the same error on sidecar build :-(

**Comment by ericwill** [comment]
> @ericwill there is still the same error on sidecar build :-(

Yep, the build needs to be fixed. Please stand by. :)

**Comment by benoitf** [comment]
@apupier could you rebase your branch ? (or I can do it for you if you checked the box)

**Comment by apupier** [comment]
> could you rebase your branch ? (or I can do it for you if you checked the box)

I will rebase.

Isn't the box on teh right that you are mentioning?
Screenshot from 2021-02-25 16-26-57

**Comment by benoitf** [comment]
@apupier yes it was this checkbox  !
if you didn't had time I would have rebase your branch against main branch

**Review by ericwill — APPROVED** [review]

**Pull request merged**
