### PR TITLE
code-server: update to 2.1692-vsc1.39.2

### PR DESCRIPTION
**Pull request by sr229**
### What does this PR do?

Updates code-server to update to 2.1692-vsc1.39.2.

### CODE REVIEW

**Comment by sr229** [comment]
I noticed the OpenShift.io versions are not yet updated as well so it might be nice to update the Registry copy of OpenShift.io once this is merged.

**Comment by sr229** [comment]
> When loading up a workspace with the editor enabled, I just get a `Enter server password` page -- what should be entered there?

I forgot to account the new behavior we introduced lately. This should be fixed now.

**Comment by sr229** [comment]
> Tested again, works now -- thanks @sr229!
> 
> There are still a few rough spots between Che and code-server, e.g. projects aren't automatically checked out (since che-machine-exec isn't used) but I can import a git project without issue.

This might need a custom stack, not exactly sure how we want VSCode to do the Eclipse Che theia behavior.

**Comment by ericwill** [comment]
Sorry that this sat around for so long @sr229. If you'd like to update the PR to the latest version I'll see that it gets in ASAP.

**Comment by sr229** [comment]
Will do!

**Comment by benoitf** [comment]
@sr229 : ping ?

**Comment by benoitf** [comment]
hello,
closing this PR for now as it's outdated, please re-open with up-to-date changes

**Pull request closed without merging**
