### PR TITLE
Make intellij endpoint not discoverable to allow running >1 Workspaces

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Allows running >1 Workspaces with IntelliJ Che Editor by declaring its endpoint not discoverable.

### What issues does this PR fix or reference?

see the details in https://github.com/eclipse/che/issues/18347

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
I would bump as well the sidecar to a more recent one if possible

**Comment by azatsarynnyy** [comment]
> I would bump as well the sidecar to a more recent one if possible

good idea, but not now I guess :wink:

**Comment by azatsarynnyy** [comment]
[ci-test]

**Comment by benoitf** [comment]
you can skip the result of ci.centos jobs @azatsarynnyy

**Comment by benoitf** [comment]
@ericwill seems an icon not related to this PR is now missing: https://raw.githubusercontent.com/spgennard/vscode_cobol/v5.2.2/images/cobol.png

**Comment by azatsarynnyy** [comment]
> you can skip the result of ci.centos jobs @azatsarynnyy

@benoitf even `e2e - Happy path`?

**Comment by benoitf** [comment]
@azatsarynnyy yes it doesn't work since 2 months on this repo.

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy yes it doesn't work since 2 months on this repo.

okay, merging then
thx!

**Pull request merged**
