### PR TITLE
Set 7.0.0-next version of Che Theia image 

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### What does this PR do?

According to the https://github.com/eclipse/che-theia/pull/347 need to use new Che Theia image

### CODE REVIEW

**Comment by benoitf** [comment]
should it be instead 7.0.0-RC4-SNAPSHOT something like 7.0.0-nightly or 7.0.0-next ?
AFAIK images have never used the tag SNAPSHOT but nightly/latest/next

**Comment by benoitf** [comment]
also it's unclear how release are made from che-theia branch, I didn't see update on https://github.com/eclipse/che/issues/13782

with SNAPSHOT name I don't know if it is on each commit, every night, etc

**Comment by vparfonov** [comment]
> should it be instead 7.0.0-RC4-SNAPSHOT something like 7.0.0-nightly or 7.0.0-next ?
> AFAIK images have never used the tag SNAPSHOT but nightly/latest/next

see here https://github.com/eclipse/che-theia/pull/347/files#diff-0f90e09c9296ab5840fb280db0cad7c6R17 please

**Comment by benoitf** [comment]
yes I see where it was but it didn't ring the bell when I saw it.

**Pull request merged**
