### PR TITLE
Bump sidecar copyright headers to 2021

### PR DESCRIPTION
**Pull request by ericwill**
Signed-off-by: Eric Williams <ericwill@redhat.com>

### What does this PR do?
Bumps sidecar copyright headers to 2021, if applicable. This is needed to ensure a valid build for when all non-sidecar headers are updated.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by ericwill** [comment]
@benoitf I think we need to tweak the sidecar check part of the plugin registry build -- even updating a simple sidecar on its own will fail the build as the SHA1 ID does not yet exist.

**Comment by benoitf** [comment]
Maybe image should not be built when we only modify sidecar/** folders

**Comment by benoitf** [comment]
I mean it should not trigger the workflow

**Comment by ericwill** [comment]
> I mean it should not trigger the workflow

Agreed, at least for now until we sort out whether we want to enable parallel updating.

**Comment by benoitf** [comment]
@ericwill let's rebase your branch, should work now

**Comment by benoitf** [comment]
hmm ok it may not work as expected if github still wait for a workflow but workflow is not triggered...

**Comment by ericwill** [comment]
> hmm ok it may not work as expected if github still wait for a workflow but workflow is not triggered...

I suppose this is because the workflow is required, right?

**Comment by benoitf** [comment]
yes.

**Comment by benoitf** [comment]
@ericwill if you can do a new rebase. Thanks

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
seems PR build check is failing on sidecars

**Comment by ericwill** [comment]
> seems PR build check is failing on sidecars

I've retriggered to see if it's a one-off

**Comment by ericwill** [comment]
> > seems PR build check is failing on sidecars
> 
> I've retriggered to see if it's a one-off

Ah I remember why this fails now -- the builds take too long and just die eventually. I remember I had this issue when I first contributed the sidecars, so I had to do them in batches. Since it's just a copyright change, do we need to break them up into separate PRs, or can I just merge as is? cc @benoitf

**Comment by benoitf** [comment]
if build dies when it's in master it means we will never get images published so maybe break it apart or we don't update copyright there until files are changed

**Comment by ericwill** [comment]
> if build dies when it's in master it means we will never get images published so maybe break it apart or we don't update copyright there until files are changed

Okay, coming to think of it the copyright bump was mostly for downstream sync work, but these sidecar definitions will never be synced. I'll close this PR and we can just have them updated when they are modified.

**Pull request closed without merging**
