### PR TITLE
Upgrade Language Support for Apache Camel extension to 0.0.28

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by apupier** [comment]
errors are unrelated to this PR:

```
› Current Kubernetes context: 'eclipse-che/192-168-42-224:8443/developer'
    Error: There is no active login session. Please use "server:login" first.
Connection to 172.19.2.159 closed.
```

```
{
  "msg": "Exceeded maximum allowed fail nodes limit,                        please release other machines to continue"
}
```

**Comment by nickboldt** [comment]
Could we just replace 0.0.27 with 0.0.28 instead of adding a new one and deprecating the previous, like we do in CRW now?

**Comment by ericwill** [comment]
> Could we just replace 0.0.27 with 0.0.28 instead of adding a new one and deprecating the previous, like we do in CRW now?

Upstream we aren't that far...yet. :wink: Soon!

**Review by ericwill — APPROVED** [review]

**Comment by nickboldt** [comment]
equivalent fix in downstream: https://github.com/redhat-developer/codeready-workspaces/commit/cccb3105cad4eb66da3fa68c6688b2452efc2f5f

**Pull request merged**
