### PR TITLE
Upgrade VS Code Metals, the Scala language client, to version 1.9.9

### PR DESCRIPTION
**Pull request by sideeffffect**
Signed-off-by: sideeffffect <ondra.pelech@gmail.com>

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by benoitf** [comment]
hello @sideeffffect , could you please keep the github pull request template in place ?

**Comment by sideeffffect** [comment]
how do I bring it back?

**Comment by benoitf** [comment]
@sideeffffect you can find it there: https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by sideeffffect** [comment]
it's back

**Comment by benoitf** [comment]
@sideeffffect but alls sections including `how to test` are empty

**Comment by sideeffffect** [comment]
@ericwill can you please have a look at this? :pray:

**Review by ericwill — APPROVED** [review]
In the future, please keep the PR template intact :slightly_smiling_face:

**Pull request merged**
