### PR TITLE
feat(build/report): verbose mode when building

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Enhance traces displayed when building registry

### Screenshot/screencast of this PR
https://user-images.githubusercontent.com/436777/106483365-bd6c2380-64ae-11eb-9399-c6cc2f0780b6.mp4

### What issues does this PR fix or reference?
https://github.com/eclipse/che-plugin-registry/pull/815#pullrequestreview-578269305

### How to test this PR?
launch ./build.sh

you should have progress items

note: it should work fine only if you've currently cached items of downloaded vsix files (else you'll hit openvsx removal extension issue)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

Change-Id: I0f3400f1b996055a84168b9b1a3c87ef49c01726
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by sunix** [comment]
nice !
Selection_187

**Comment by sunix** [comment]
It would be nice to see a message when it is done. Something like.

> Done generating plugin registry, check out the `/projects/che-plugin-registry/output` folder.

Selection_189

**Review by sunix — APPROVED** [review]
Looks good to me as it is. Improvement to have a `done` message at the end is optional and nice to have but not blocker.

**Comment by benoitf** [comment]
```
🎉 Successfully generated in ../che-plugin-registry/output. Took a minute.
```

**Comment by sunix** [comment]
Selection_190

nice !!!
merge it !!! :D

**Review by ericwill — APPROVED** [review]

**Pull request merged**
