### PR TITLE
Plantuml extension

### PR DESCRIPTION
**Pull request by gattytto**
Signed-off-by: Esteban Mañaricua <emanaricua@gmail.com>
Add plantUML extension to che-plugin-registry.
Closes https://github.com/eclipse/che/issues/17916
Signed-off-by: Esteban Mañaricua <emanaricua@gmail.com>

### CODE REVIEW

**Comment by ericwill** [comment]
This one is blocked by https://github.com/eclipse/che/issues/17931

**Comment by gattytto** [comment]
https://github.com/eclipse/che/issues/17931 was a duplicate of the actuall blocker https://github.com/eclipse/che/issues/16870

**Comment by vzhukovs** [comment]
Hi @gattytto, I've checked provided in this PR VS Code extension, I've got the following result:

Eclipse Che hosted by Red Hat | 2020-12-21 02-41-24

You can check how it works on your side.

**Comment by azatsarynnyy** [comment]
Note, it can be verified against `che-theia:next` ATM as the corresponding issue has been recently fixed - https://github.com/eclipse/che/issues/16870 and will be released as part of Che 7.24

**Comment by gattytto** [comment]
I will check and come back ASAP

**Comment by gattytto** [comment]
this PR needs refactoring, BRB.

**Pull request closed without merging**
