### PR TITLE
Node debug

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
### What does this PR do?
Add
- ms-vscode/node-debug2 **v1.42.5**
- ms-vscode/node-debug **v1.44.8**

### How to test this PR?

Use following devfile to test this PR
```
---
apiVersion: 1.0.0
metadata:
  generateName: nodejs-
projects:
  -
    name: nodejs-web-app
    source:
      type: git
      location: "https://github.com/che-samples/web-nodejs-sample.git"
components:
  -
    type: chePlugin
    id: che-incubator/typescript/latest
    memoryLimit: 512Mi
  - 
    type: chePlugin
    # id: ms-vscode/node-debug2/latest
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/node-debug/v3/plugins/ms-vscode/node-debug2/1.42.5/meta.yaml
    preferences:
      debug.node.useV3: false
  -
    type: dockerimage
    alias: nodejs
    image: quay.io/eclipse/che-nodejs10-ubi:nightly
    memoryLimit: 512Mi
    endpoints:
      - name: 'nodejs'
        port: 3000
    mountSources: true
commands:
  -
    name: download dependencies
    actions:
      - type: exec
        component: nodejs
        command: npm install
        workdir: ${CHE_PROJECTS_ROOT}/nodejs-web-app/app
  -
    name: run the web app
    actions:
      - type: exec
        component: nodejs
        command: nodemon app.js
        workdir: ${CHE_PROJECTS_ROOT}/nodejs-web-app/app
  -
    name: run the web app (debugging enabled)
    actions:
      - type: exec
        component: nodejs
        command: nodemon --inspect app.js
        workdir: ${CHE_PROJECTS_ROOT}/nodejs-web-app/app
  -
    name: stop the web app
    actions:
      - type: exec
        component: nodejs
        command: >-
          node_server_pids=$(pgrep -fx '.*nodemon (--inspect )?app.js' | tr "\\n" " ") &&
          echo "Stopping node server with PIDs: ${node_server_pids}" && 
          kill -15 ${node_server_pids} &>/dev/null && echo 'Done.'
  -
    name: Attach remote debugger
    actions:
    - type: vscode-launch
      referenceContent: |
        {
          "version": "0.2.0",
          "configurations": [
            {
              "type": "node",
              "request": "attach",
              "name": "Attach to Remote",
              "address": "localhost",
              "port": 9229,
              "localRoot": "${workspaceFolder}",
              "remoteRoot": "${workspaceFolder}"
            }
          ]
        }
```

I want to pay attention, that to make node-debug plugin working properly, the workspace must have preference property `debug.node.useV3` set to false. For that we should update all the devfiles, that use node-debug plugin.
```
debug.node.useV3: false
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by JPinkney — APPROVED** [review]

**Review by ericwill — COMMENTED** [review]
No need to add a new `meta.yaml`, we are only keeping one version of each plugin in the registry now. You can just update the existing `meta.yaml` with the new version.

**Comment by vitaliy-guliy** [comment]
> No need to add a new `meta.yaml`, we are only keeping one version of each plugin in the registry now. You can just update the existing `meta.yaml` with the new version.

We have to add it, it's because this is a new **1.42.5** version.

And also I would like to add new `meta.yaml` for new version, otherwise versioning does not make any sence.
We can always cleanup old versions and just leave few latest.

**Comment by ericwill** [comment]
> > No need to add a new `meta.yaml`, we are only keeping one version of each plugin in the registry now. You can just update the existing `meta.yaml` with the new version.
> 
> We have to add it, it's because this is a new **1.42.5** version.
> 
> And also I would like to add new `meta.yaml` for new version, otherwise versioning does not make any sence.
> We can always cleanup old versions and just leave few latest.

We are only keeping the latest version of every plugin now, see eclipse/che#18183. So it's not necessary to add new `meta.yaml`  files any longer, we only need to update the single `meta.yaml` file for each plugin.

**Comment by vitaliy-guliy** [comment]
> We are only keeping the latest version of every plugin now, see [eclipse/che#18183](https://github.com/eclipse/che/issues/18183). So it's not necessary to add new `meta.yaml` files any longer, we only need to update the single `meta.yaml` file for each plugin.

Ok, but we still need should rename a directory which indicates the plugin version.

And then if we don't have versions (which is strange, but OK), we don't need to have that directory.
So, the plugin ID become
```
ms-vscode/node-debug2
```
instead
```
ms-vscode/node-debug2/latest
```
I think it's for feature.

**Comment by ericwill** [comment]
> > We are only keeping the latest version of every plugin now, see [eclipse/che#18183](https://github.com/eclipse/che/issues/18183). So it's not necessary to add new `meta.yaml` files any longer, we only need to update the single `meta.yaml` file for each plugin.
> 
> Ok, but we still need should rename a directory which indicates the plugin version.
> 
> And then if we don't have versions (which is strange, but OK), we don't need to have that directory.
> So, the plugin ID become
> 
> ```
> ms-vscode/node-debug2
> ```
> 
> instead
> 
> ```
> ms-vscode/node-debug2/latest
> ```
> 
> I think it's for feature.

Yes for now just keep the version in the folder name, we can play around with folder names in future PRs.

**Comment by vitaliy-guliy** [comment]
Now it looks like just updating of existent `meta.yaml`

**Review by ericwill — APPROVED** [review]
Please note that we'll need to build the extensions and host them on download.jboss.org for the CRW version of this PR.

**Comment by vitaliy-guliy** [comment]
> Please note that we'll need to build the extensions and host them on download.jboss.org for the CRW version of this PR.

What about download them from Open VS Registry?

**Comment by ericwill** [comment]
> > Please note that we'll need to build the extensions and host them on download.jboss.org for the CRW version of this PR.
> 
> What about download them from Open VS Registry?

CRW product requirements mean we have to build the extension ourselves, and use that.

**Pull request merged**
