### PR TITLE
fix(camel-k): Update images to the latest one

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
entrypoint was not executable
Fixes https://github.com/eclipse/che/issues/15455

Change-Id: Id00a2a710b626cd03158d24e66bac31b7c02e9bd
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
to help reviewing the PR, here is the link to the tags of the images updated https://quay.io/repository/eclipse/che-sidecar-camelk?tag=latest&tab=tags

**Comment by nickboldt** [comment]
My opinion is that the 0.0.9 one should be marked deprecated with auto update to the 0.0.10 one so you don't have to bother rebuilding images for old plugins.

But otherwise I have no opinion here. +0.1, looks OK.

**Comment by benoitf** [comment]
@nickboldt yes but it was failing to start container for 0.0.9

**Comment by benoitf** [comment]
@apupier is it ok to deprecate 0.0.9 in a new PR ?

**Comment by nickboldt** [comment]
but wouldn't the auto-update cause the plugin broker to pull the 0.0.10 plugin instead of the 0.0.9 one, then the 0.0.10 container? cc: @amisevsk (I'm trying to understand how the deprecate/auto-update actually works in terms of pulled containers after reading meta.yaml

**Comment by benoitf** [comment]
ok can do deprecate stuff in a new PR

**Comment by amisevsk** [comment]
@nickboldt I don't think the broker will do anything with those fields as it currently stands; the update has to come from the server-side. From what I've seen (I'm very ready to be wrong on this one), the deprecate support is only a warning on the workspace config tab.

**Comment by nickboldt** [comment]
@amisevsk then what are these for?
```
  autoMigrate:         # boolean
  migrateTo:           # new org/plugin-id/version, e.g. redhat/vscode-apache-camel/latest
```

If it's just a warning then how is the `migrateTo` useful?

**Comment by amisevsk** [comment]
@nickboldt -- as I mentioned, I'm happy to be wrong. On the other hand, I'm able to create and update workspace with the currently deprecated `camel-tooling/vscode-apache-camel` plugin. I've opened issue https://github.com/eclipse/che/issues/15461

**Pull request merged**
