### PR TITLE
Move sidecar definitions into the plugin registry (part I)

### PR DESCRIPTION
**Pull request by ericwill**
Part 1 of the migration. I am doing it in parts because doing it all at once will likely cause a build timeout upon merge.

Signed-off-by: Eric Williams <ericwill@redhat.com>

### What does this PR do?
Contributes sidecar definitions to the plugin registry.

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
eclipse/che#18217

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by ericwill** [comment]
shellcheck is going to fail due to some of the scripts for the Java sidecars -- I'm not sure if it's worth fixing them now or later.

**Comment by benoitf** [comment]
should we keep `java8` as new vscode java won't be able to use it now ?

**Comment by ericwill** [comment]
> should we keep `java8` as new vscode java won't be able to use it now ?

I would say keep it and we'll still keep two Java plugins (`java8` and `java`) until we can support older JDKs (work is in progress already).

**Comment by benoitf** [comment]
for shellcheck it looks like they're easy fix

**Comment by ericwill** [comment]
> for shellcheck it looks like they're easy fix

Will fix them in this PR then.

**Comment by benoitf** [comment]
you may do a New pr only with java ?

**Review by benoitf — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
Can't we use same default entrypoint.sh for almost all side-cars ?

**Comment by ericwill** [comment]
> you may do a New pr only with java ?

Sure will do.


> Can't we use same default entrypoint.sh for almost all side-cars ?

I was planning to switch them to fragments like in the che-theia build, but in a separate PR. I don't want to stuff too many changes into this one in case of a regression.

**Comment by ericwill** [comment]
First set of sidecars published :partying_face: 

https://quay.io/repository/eclipse/che-plugin-sidecar?tag=latest&tab=tags

**Pull request merged**
