### PR TITLE
Committing latest meta.yaml files for VsCode 3.5.0 to 3.6.2

### PR DESCRIPTION
**Pull request by AbhiAuto**
### What does this PR do?
This PR is for latest VS Code plugin for Eclipse Che

### What issues does this PR fix or reference?

It will help the testing community to leverage the Eclipse Che with VS Code for their test automation development and execution using TestNG and JUnit. As Java "https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test" is not compatible with the existing version of VS Code currently in the plugin registry repository.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by ericwill** [comment]
Hi, thanks for the PR. Is there any reason you are adding multiple versions? Generally only the latest version is fine. :+1:

**Comment by AbhiAuto** [comment]
> Hi, thanks for the PR. Is there any reason you are adding multiple versions? Generally only the latest version is fine. 👍
Yes, eric. We are not sure about the automation test plugins for TestNG/Junit of Java/C# would work with which version of vscode. So we thought to have latest 5 versions, whichever it would work we can use in our development process.

**Comment by ericwill** [comment]
> > Hi, thanks for the PR. Is there any reason you are adding multiple versions? Generally only the latest version is fine. +1
> > Yes, eric. We are not sure about the automation test plugins for TestNG/Junit of Java/C# would work with which version of vscode. So we thought to have latest 5 versions, whichever it would work we can use in our development process.

Ideally we should only have the working version, instead of committing 5 possible versions. Can you test on your end and narrow down which version you'd like to contribute?

**Comment by AbhiAuto** [comment]
> > > Hi, thanks for the PR. Is there any reason you are adding multiple versions? Generally only the latest version is fine. +1
> > > Yes, eric. We are not sure about the automation test plugins for TestNG/Junit of Java/C# would work with which version of vscode. So we thought to have latest 5 versions, whichever it would work we can use in our development process.
> 
> Ideally we should only have the working version, instead of committing 5 possible versions. Can you test on your end and narrow down which version you'd like to contribute?

Hi Eric

We are good to go with 3.6.2 version which is the latest one. Please let me know if I need to do any modifications.

**Comment by benoitf** [comment]
@AbhiAuto let's keep only 3.6.2 and check your eclipse eca

**Comment by AbhiAuto** [comment]
> @AbhiAuto let's keep only 3.6.2 and check your eclipse eca

Hi, 

I have removed other versions. Please let me know if we are good to go with the latest changes.

**Comment by benoitf** [comment]
@AbhiAuto you still have missing ECA signature
image

**Comment by AbhiAuto** [comment]
I will raise a new pull request, as I missed a few basic ECA in committing files.

**Comment by benoitf** [comment]
you may just use 'force-push' and squash your commits

**Pull request closed without merging**
