### PR TITLE
Don't rewrite image digests for images we can't read

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Cherry-pick commit https://github.com/amisevsk/che-plugin-registry/pull/new/digests-7.9.x (PR https://github.com/eclipse/che-plugin-registry/pull/420) to release branch

### What issues does this PR fix or reference?
eclipse/che#16281

### CODE REVIEW

**Comment by nickboldt** [comment]
dupe of #420

**Comment by amisevsk** [comment]
@nickboldt this is for the release branch.

**Comment by nickboldt** [comment]
we don't do PRs for release branch!

We just force push https://github.com/eclipse/che-plugin-registry/blob/master/make-release.sh

**Comment by amisevsk** [comment]
@nickboldt what do you mean? We need to cherry-pick commits into 7.9.x branch before running `make-release.sh`.

**Comment by nickboldt** [comment]
*nods*

```
* 2cec5f4 - (HEAD -> master, origin/master, origin/HEAD) Don't rewrite image digests for images we can't read amisevsk@redhat.com (4 days ago)
```

Done 4 days ago :)

**Comment by amisevsk** [comment]
I mean, it's your process, but that sounds like it's gonna be very prone to error. Why not just merge PRs that can be searched/linked in issues?

**Comment by nickboldt** [comment]
I agree, that's better. But this one previously had target branch of master, not 7.9.x :D that's why I closed it originally as I assumed it was a dupe. 

In future, sure, PRs are great. I also like manually cherrypicked and pushed commits if done at the same time the master PR is approved.

**Pull request closed without merging**
