### PR TITLE
Update VSCode-YAML to 0.11.1

### PR DESCRIPTION
**Pull request by JPinkney**
### What does this PR do?
This PR does a few things for VSCode-YAML:
- Updates VSCode-YAML to 0.11.1
- Removes references of Kedge from the description (It hasn't been supported in a long time) 
- Removes 0.4.0 though I don't know the policy on this one. Should I just remove the folder or do I need to do anything else? It's been a long time since I've updated the plugin.

For some reason git thinks I just changed the 0.4.0 folder even though I created a new folder and added the new 0.11.1 meta.yaml in there :shrug: 

Also, there are quite a few extensions that rely on vscode-yaml 0.4.0 should I update the version in those meta.yamls as well?

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18143

### How to test this PR?

Tested on che.openshift.io

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [X] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [X] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [X] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [X] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [X] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [X] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [X] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [X] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [X] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by ericwill** [comment]
> Also, there are quite a few extensions that rely on vscode-yaml 0.4.0 should I update the version in those meta.yamls as well?

If there aren't any breaking changes in newer versions of vscode-yaml, then yes that would be appreciated :+1:

**Comment by ericwill** [comment]
Are you updating only the `0.4.0` ones or all the vscode-yaml deps to `0.11.1`?

**Comment by JPinkney** [comment]
I've just done the 0.4.0 ones currently, I could update them all to 0.11.1 and nothing _should_ break but I don't have the time right now to actually go in and verify that updating the ~10 ish other extension versions to 0.11.1 doesn't break anything

**Comment by ericwill** [comment]
> I've just done the 0.4.0 ones currently, I could update them all to 0.11.1 and nothing _should_ break but I don't have the time right now to actually go in and verify that updating the ~10 ish other extension versions to 0.11.1 doesn't break anything

No worries, sounds good. Thanks for the PR.

**Review by ericwill — APPROVED** [review]

**Pull request merged**
