### PR TITLE
[release] Bump to 7.12.0-SNAPSHOT in master

### PR DESCRIPTION
**Pull request by ericwill**
Signed-off-by: Eric Williams <ericwill@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
FYI eca fails

Anonymous (ericwill@****.localdomain) is not covered by the necessary legal agreements in order to proceed.

**Comment by ericwill** [comment]
> FYI eca fails
> 
> Anonymous (ericwill@****.localdomain) is not covered by the necessary legal agreements in order to proceed.

I edited the message to have the correct sign-off.

**Comment by benoitf** [comment]
@ericwill it needs to be changed in the commit message

**Comment by ericwill** [comment]
Let me close this one and do a new one, I forgot to set my git config on my new laptop.

**Comment by benoitf** [comment]
you can just amend your commit and force push

**Pull request closed without merging**
