### PR TITLE
Update Kubernetes plugin to use vscode-kubernetes-tools 1.0.9

### PR DESCRIPTION
**Pull request by ericwill**
Add a new version of the vscode-kubernetes-tools plugin (1.0.9) which includes support for helm 3.

See eclipse/che#15190

Signed-off-by: Eric Williams <ericwill@redhat.com>

### CODE REVIEW

**Comment by ericwill** [comment]
> Looks good but this is one of the 3rd party plugins that we're now building and publishing to download.jboss.org so that we can control the co-location when publishing of source and binary artifacts (to make Prod Sec happy). Hey, @mkuznyetsov can you build one more vsix for @ericwill ? Or teach him how to run your job? :)

I'd be up for trying to build it myself, just point me in the right direction :)

**Comment by mkuznyetsov** [comment]
@ericwill I've built and published the 1.0.9 version on dl.jboss.org, so it is available here: https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-kubernetes-tools/

The doc on how to operate the related CI job will be coming soon as well

**Comment by ericwill** [comment]
> @ericwill I've built and published the 1.0.9 version on dl.jboss.org, so it is available here: https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-kubernetes-tools/
> 
> The doc on how to operate the related CI job will be coming soon as well

Thanks! Will update the PR in a bit.

**Comment by nickboldt** [comment]
(Next time there will be docs in place so you can DIY, Eric. Thanks again for offering to learn/help. Mykhailo was tweaking the job and wanted to use this new build as an opportunity to test the improved job workflow.)

**Comment by ericwill** [comment]
> (Next time there will be docs in place so you can DIY, Eric. Thanks again for offering to learn/help. Mykhailo was tweaking the job and wanted to use this new build as an opportunity to test the improved job workflow.)

Not a problem! :)

**Pull request merged**
