### PR TITLE
Upgrade Didact extension to 0.2.0

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

### What does this PR do?
Updates the vscode-didact plugin to 0.2.0, which was just released

### Screenshot/screencast of this PR

demo 2020-12-16 13-05

### What issues does this PR fix or reference?

- Updated AsciiDoc demo with better requirements label example. [FUSETOOLS2-800](https://issues.redhat.com/browse/FUSETOOLS2-800)
- Addressed issue where inner label on adoc was updating incorrectly. [FUSETOOLS2-877](https://issues.redhat.com/browse/FUSETOOLS2-877)
- Removed local copy of asciidoctor.css in favor of using upstream version directly. [FUSETOOLS2-874](https://issues.redhat.com/browse/FUSETOOLS2-874)
- Fixed issue with platform neutral paths preventing successful operation on Windows. [FUSETOOLS-887](https://issues.redhat.com/browse/FUSETOOLS2-887)
- Added Didact icon to Didact view tab and Didact version to footer. [FUSETOOLS2-919](https://issues.redhat.com/browse/FUSETOOLS2-919)
- Added Didact icon to tutorials in tutorials view. [FUSETOOLS2-920](https://issues.redhat.com/browse/FUSETOOLS2-920)

### How to test this PR?

Open a che instance that references this PR and verify that the tutorials that appear in the tutorials view are able to be opened and run

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by bfitzpat** [comment]
Not quite sure how to specify my che.openshift.io devfile to identify this particular contribution myself. :) Any suggestions on what I would need to change to pull in the 0.2.0 version?

```
apiVersion: 1.0.0
metadata:
  name: wkspc-didact
attributes:
  persistVolumes: 'false'
components:
  - type: chePlugin
    reference: 'https://raw.githubusercontent.com/eclipse/che-plugin-registry/8dfc2ec48a94e1877588e6af1ca0131b576299ae/v3/plugins/redhat/vscode-didact/0.1.16/meta.yaml'
  - mountSources: true
    endpoints:
      - name: angular
        port: 4200
    memoryLimit: 1Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-nodejs10-community:nightly'
    alias: nodejs
  - id: che-incubator/typescript/latest
    type: chePlugin
```

**Comment by benoitf** [comment]
Hello @bfitzpat on every PR, there is a build job and a publish job so you can have your new version live after waiting some minutes on the PR check `@github-actions surge(alpine) — Browse registry content (alpine) live` for example

https://pr-check-773-alpine-che-plugin-registry.surge.sh/v3/plugins/redhat/vscode-didact/0.2.0/meta.yaml

**Comment by bfitzpat** [comment]
chedemo-2020-12-17 09-38

**Comment by benoitf** [comment]
@bfitzpat you may share the devfile (or update your previous comment with a devfile) you used with https://pr-check-773-alpine-che-plugin-registry.surge.sh/v3/plugins/redhat/vscode-didact/0.2.0/meta.yaml

**Comment by bfitzpat** [comment]
@benoitf I just modified the earlier devfile to:

```
apiVersion: 1.0.0
metadata:
  name: wkspc-didact
attributes:
  persistVolumes: 'false'
components:
  - type: chePlugin
    reference: 'https://pr-check-773-alpine-che-plugin-registry.surge.sh/v3/plugins/redhat/vscode-didact/0.2.0/meta.yaml'
  - mountSources: true
    endpoints:
      - name: angular
        port: 4200
    memoryLimit: 1Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-nodejs10-community:nightly'
    alias: nodejs
  - id: che-incubator/typescript/latest
    type: chePlugin

```

**Comment by benoitf** [comment]
I've this bottom right popup when trying on che.openshift.io
image

**Comment by benoitf** [comment]
I have something that is working image

but would be better without the popup

**Comment by bfitzpat** [comment]
@benoitf I saw that popup as well. I'm not seeing it in the non-Che version, so I'm not quite sure where that's coming from exactly. Not seeing any kind of console output that would be useful in debugging. Suggestions?

**Comment by benoitf** [comment]
image

**Comment by bfitzpat** [comment]
@benoitf Should I explore this to fix it in a 0.2.1 release? (Guessing yes) Obviously I can't fix it in the 0.2.0, which is already built and out there. I will likely not be able to get this resolved before I disappear on PTO for the holidays tomorrow afternoon

**Comment by bfitzpat** [comment]
@benoitf Ultimately it looks like the vscode.ExtensionContext.globalStorageUri is not set (i.e. it's undefined). Is there an alternative for storing things like cached files in a che workspace?

**Comment by bfitzpat** [comment]
> @benoitf Ultimately it looks like the vscode.ExtensionContext.globalStorageUri is not set (i.e. it's undefined). Is there an alternative for storing things like cached files in a che workspace?

Looks like vscode.ExtensionContext.storageUri is set on a per-workspace basis in the VS Code API... do we know if that is initialized in a che workspace?

**Comment by bfitzpat** [comment]
Unsupported options at this point in theia. @azatsarynnyy has opened https://github.com/eclipse-theia/theia/issues/8883 to address it

**Comment by ericwill** [comment]
@bfitzpat I take we should probably wait until eclipse-theia/theia#8883 is implemented before merging this?

**Comment by bfitzpat** [comment]
> @bfitzpat I take we should probably wait until [eclipse-theia/theia#8883](https://github.com/eclipse-theia/theia/issues/8883) is implemented before merging this?

Yes, I think so @ericwill

**Comment by ericwill** [comment]
Superseded by #826

**Pull request closed without merging**
