### PR TITLE
chore(build-check): Add check script to verify that docker images used in registry are valid

### PR DESCRIPTION
**Pull request by sunix**
Signed-off-by: Sun Tan <sutan@redhat.com>

### What does this PR do?
Check that each images used in the registry are valid

### Screenshot/screencast of this PR
Selection_179

Failing:
Selection_180

### What issues does this PR fix or reference?

Fix https://github.com/eclipse/che/issues/18747

### How to test this PR?
- Clone the repo and checkout the branch of this PR
- build the registry image
- check that it is working fine
- change https://github.com/eclipse/che-plugin-registry/blob/835b5318669141b43c6ca2013224d69fac6000cd/che-theia-plugins.yaml#L320, replacing `quay.io/windupeng/mta-vscode-extension:latest` with `quay.io/windupeng/mta-vscode-extension:wrongtag`
- restart the build and see that it is failing

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ericwill — COMMENTED** [review]
Hey Sun, a few things:
* We have a PR check that runs `digest-validation-pr.sh`. After this change it won't be needed (build runs on every PR) so it can be removed
* If the build runs with `USE_DIGESTS=true`, then `skopeo inspect` will be run twice -- maybe run yours only if `USE_DIGESTS=false`?
    * In other places where `skopeo inspect` is called, the option `--tls-verify=false` is specified. Do we need that here too?

**Comment by benoitf** [comment]
FYI i've an upcoming PR that remove all .sh scripts, everything being checked when generating files.

**Comment by sunix** [comment]
I suggest that we postpone the work to be done for these checks, and see/discuss what to do after Florent's PR merged. @ericwill works for you?

**Comment by ericwill** [comment]
> I suggest that we postpone the work to be done for these checks, and see/discuss what to do after Florent's PR merged. @ericwill works for you?

Sounds good to me.

**Comment by benoitf** [comment]
FYI https://github.com/eclipse/che-plugin-registry/pull/815 here is the relate PR

**Comment by sunix** [comment]
@benoitf could you confirm that these checks won't be necessary anymore with https://github.com/eclipse/che-plugin-registry/pull/815 ?

**Comment by benoitf** [comment]
yes I confirm that as digests are retrieved, it's ensuring that the image/tag do exists
If not, there will be a build failure

**Comment by sunix** [comment]
> yes I confirm that as digests are retrieved, it's ensuring that the image/tag do exists
> If not, there will be a build failure

OK I am closing this one so

**Pull request closed without merging**
