### PR TITLE
Added docker buildx support in cico

### PR DESCRIPTION
**Pull request by Prabhav-Thali**
Signed-off-by: Prabhav Thali <Prabhav.Thali1@ibm.com>

### What does this PR do?
Adds docker buildx support in cico scripts to build multi-arch images.

### CODE REVIEW

**Comment by Prabhav-Thali** [comment]
[ci-test]

**Comment by ericwill** [comment]
@Prabhav-Thali can you rebase your PR please?

**Comment by Prabhav-Thali** [comment]
@ericwill I have updated the PR.

**Comment by ericwill** [comment]
Thanks! The PR appears to be a failing the shellcheck -- can you take a look?

**Comment by benoitf** [comment]
as ci.centos.org is being shut-downed before end the year I would not add new stuff there.

**Comment by Prabhav-Thali** [comment]
@benoitf Thanks for the clarification. Could you please let us know whats your plan after ci.centos.org sunset and how we can enable s390x support to Che docker images?

**Comment by benoitf** [comment]
@Prabhav-Thali moving to github actions with buildx support

**Comment by nickboldt** [comment]
As the cico scripts are no longer being maintained (centos CI is EOL), this PR will never be merged.

Instead, please submit a new PR with code that calls a PLATFORMS file and runs buildx like this:

https://github.com/eclipse/che-plugin-registry/blob/master/.ci/sidecar-build-publish.sh#L31-L35
or like this:

https://github.com/che-incubator/che-dashboard-next/blob/master/.github/workflows/dockerimage.yml#L35
---

See also: 

* https://github.com/eclipse/che-devfile-registry/pull/250#issuecomment-740180491 (similar PR for dockerx in centos CI)

PR to move to GH action in plugin registry: 

* https://github.com/eclipse/che-plugin-registry/pull/723

**Pull request closed without merging**
