### PR TITLE
Configure default cpuLimit and cpuRequest

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
Configure default values for `cpuLimit: 1500m` and `cpuRequest: 500m` for next tag image.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18565

### How to test this PR?
Create a workspace from the [provided](https://gist.github.com/vzhukovs/b84da9a20b60386bc2145e25d8df88ad/raw/b57af34a6c6418d698f24babe2d62da6f0bf7592/workspace-2.yaml) devfile, workspace should be able to start.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by ericwill** [comment]
Was it tested on RHPDS and the dogfooding environment?

**Comment by vzhukovs** [comment]
@ericwill it was tested on RHPDS, but for RHPDS meta.yaml for the theia-editor needs to be a bit modified. To provide cpuLimit: 1.5 and cpuRequest 0.5. Because there was a fix for 7.23 which provides correct cpu configuration conversion, but che on RHPDS is 7.20.2

Red Hat OpenShift Container Platform 2021-01-18 21-01-56

As for dogfooding instance. I'm trying to get an access to this host. Will post results of check asap.

**Comment by vzhukovs** [comment]
Tested on dogfooding instance:
Red Hat OpenShift Dedicated 2021-01-19 14-14-53

**Review by azatsarynnyy — COMMENTED** [review]
I also checked it on our internal dogfooding instance.
LGTM, but up to @ericwill

**Review by azatsarynnyy — APPROVED** [review]

**Review by ericwill — APPROVED** [review]
Sorry, forgot to review this yesterday. LGTM.

**Pull request merged**
