### PR TITLE
Update versions of editors/plugin

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Update versions of editors/plugin

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Should we upgrade a version of plugins and editors itself for such radical change? Wdyt @garagatyi @benoitf @l0rd ?

**Comment by benoitf** [comment]
I think it will make extra work (update every stacks ?)

**Comment by garagatyi** [comment]
@skabashnyuk No, we don't have plugins update policies for workspaces which mean that users would be stuck with old plugins.

**Comment by garagatyi** [comment]
BTW UD shows all the versions of the same plugin. See
image
@slemeur FYI

**Pull request merged**
