### PR TITLE
Update didact to version 0.3.1

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

### What does this PR do?

Adds latest version of the vscode-didact extension, which enables multi-tutorial window functionality and revises the method of behind-the-scenes caching used between sessions to hopefully avoid falling into the hole of https://github.com/eclipse-theia/theia/issues/8883

### Screenshot/screencast of this PR

new-demo-04-FEB-2021

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by bfitzpat** [comment]
Creating this PR to test the newer version of Didact in che/theia online with version 0.3.0

**Comment by bfitzpat** [comment]
Not quite sure how to fix this so things are happier with all the checks. Please holler if there's anything you need me to do. :) Thanks!

**Comment by bfitzpat** [comment]
Updated to stable release path https://download.jboss.org/jbosstools/vscode/stable/vscode-didact/vscode-didact-0.3.1-166.vsix

**Comment by bfitzpat** [comment]
What's the best way to test this since the happy path builds timed out?

**Comment by ericwill** [comment]
> What's the best way to test this since the happy path builds timed out?

Launch Che and use the didact plugin `meta.yaml` from surge.sh: https://pr-check-826-alpine-che-plugin-registry.surge.sh/v3/plugins/redhat/vscode-didact/latest/meta.yaml

Every PR in the plugin registry is built and published to surge, and the URL to this is based on the PR number. In this case you can see the hosted plugin registry on surge at: https://pr-check-826-alpine-che-plugin-registry.surge.sh/

**Comment by bfitzpat** [comment]
All seems to run well - and no issues with caching like we had in 0.2.0! 
che-demo-feb-2021

**Review by ericwill — APPROVED** [review]

**Pull request merged**
