### PR TITLE
don't attempt to open a web browser for the...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?
don't attempt to open a web browser for the generated PR, since this is expected to be run headless as a Jenkins job / GH action

Change-Id: I43686a7f2025491029ba3e5a2d2730e5e79157b5
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ericwill — APPROVED** [review]

**Review by benoitf — CHANGES_REQUESTED** [review]
please use PR template
Thx

**Comment by nickboldt** [comment]
@benoitf it's a TWO CHARACTER change to suppress automatically opening a browser when a PR is created. 

You reallllly need me to follow a template for that?

**Comment by benoitf** [comment]
Yes as for any PRs

Because title is cropped
It's not consistent
We all agreed on templates but you never use those even on bigger PRs

**Comment by benoitf** [comment]
@nickboldt how to test and what the issue is would be really useful

Goals of PR template were to make sure PR are self explanatory and that reviewers tell how they test

It looks there is like 'automatic approval' without saying how to test, if it has been tested

**Review by benoitf — DISMISSED** [review]

**Pull request merged**
