### PR TITLE
allow non millicore values in cpu limit/request

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
Fix regex validating cpu limit/request to allow non-millicore values

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18488

### How to test this PR?

1. add cpu limit or request to some plugin in whole cores, like `0.03`
1. run validation with `./check_metas_schema.sh` script

**valid values** - `11`, `1`, `1.1`, `0.1`, `0.01`, `1m`, `100m`, `1000m`
**invalid values** - `1.1.1`, `1.1m`, `0m`, `1k`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
@sparkoo do you have examples of valid and invalid values? It could simplify work for reviewers.

**Review by ibuziuk — COMMENTED** [review]
might be worth updating README - https://github.com/eclipse/che-plugin-registry#plugin-meta-yaml-structure

**Comment by sparkoo** [comment]
> @sparkoo do you have examples of valid and invalid values? It could simplify work for reviewers.

updated *How to test* section

**Comment by sparkoo** [comment]
> might be worth updating README - https://github.com/eclipse/che-plugin-registry#plugin-meta-yaml-structure

done

**Review by vitaliy-guliy — APPROVED** [review]
Works as expected.
BTW, tested with '01m', which seems to be a correct value to be used under the hood
```
   '01m' does not match '^[0-9]+(\\.[0-9]+)?$|^[1-9][0-9]*m$'
```
But it's not a big deal, user should set values as short as possible.

**Review by ibuziuk — APPROVED** [review]
:+1:

**Comment by benoitf** [comment]
Hello, it seems 0m is a valid quantity

```go
package main

import (
        "fmt"
        "k8s.io/apimachinery/pkg/api/resource"
)

func main() {
  cores := resource.MustParse("5300m")
  fmt.Printf("milliCores = %v (%v)\n", cores.MilliValue(), cores.Format)
  cores = resource.MustParse("0")
  fmt.Printf("milliCores = %v (%v)\n", cores.MilliValue(), cores.Format)
  cores = resource.MustParse("5.3")
  fmt.Printf("milliCores = %v (%v)\n", cores.MilliValue(), cores.Format)
  cores = resource.MustParse("0m")
  fmt.Printf("milliCores = %v (%v)\n", cores.MilliValue(), cores.Format)

}
```

```
$ ./cpu 
milliCores = 5300 (DecimalSI)
milliCores = 0 (DecimalSI)
milliCores = 5300 (DecimalSI)
milliCores = 0 (DecimalSI)
```
And If I enter an invalid quantity I've:
panic: cannot parse '1.1.1': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

**Comment by benoitf** [comment]
also 1k seems to be a valid value in kubernetes world (or `0.001k`)
maybe we could use the same regexp than the `kubectl` tool for memory or cpu

**Comment by sparkoo** [comment]
we can but currently che can handle just 'm'

**Comment by benoitf** [comment]
ok so then we fix che to allow same range than k8s allow and then we can fix it as well.
Better to not use different regexp than what underlying system allow.

**Comment by sparkoo** [comment]
> ok so then we fix che to allow same range than k8s allow and then we can fix it as well.
> Better to not use different regexp than what underlying system allow.

I agree, but can we do it in separate issue? It will be more non-trivial work on at least 2 components. This PR is quick and easy fix that will allow to move forward with https://github.com/eclipse/che-plugin-registry/pull/716

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
I created https://github.com/eclipse/che/issues/18541 for the expected regexp

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
