### PR TITLE
provide new VS Code Camel version 0.0.24 eclipse/che#17141

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### What does this PR do?

TODO

### CODE REVIEW

**Comment by apupier** [comment]
I don't get the link of the failure for ci.centos.org PR check (language plugin tests) and my PR

`/bin/bash: .ci/cico-plugin-registry-pr-test.sh: No such file or directory`

**Comment by ericwill** [comment]
> I don't get the link of the failure for ci.centos.org PR check (language plugin tests) and my PR
> 
> `/bin/bash: .ci/cico-plugin-registry-pr-test.sh: No such file or directory`

They aren't working for now so they will always fail.

Is this PR ready for review @apupier?

**Comment by ericwill** [comment]
Also, I think this one has been deprecated for more than 3 sprints, so let's remove it: https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/meta.yaml

**Comment by apupier** [comment]
> Is this PR ready for review @apupier?

As the failing job is not due to this PR, yes it is ready for review

> Also, I think this one has been deprecated for more than 3 sprints, so let's remove it: https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/meta.yaml

fine with that. i think it should be done in a separate PR

**Pull request merged**
