### PR TITLE
feat(vscode-plugins): add rust plugin

### PR DESCRIPTION
**Pull request by sunix**
### What does this PR do?
Adding rust plugin with rust language support (autocomplete, etc ...)

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17069

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sunix** [comment]
ok :) will fix that to yaml tomorow.

**Comment by sunix** [comment]
to test it:
- create a new workspace from the rust stack
- add the component: 
    ```yaml
    - type: chePlugin
      reference: 'https://gist.github.com/sunix/eb86fdf6802afbfb4de059ed19f08d37/raw/3c22660346e4ef67d76b7d19aa2bd84c536fcca7/meta.yaml'ml
    ```
- start the workspace and open the file `HelloWorld-Rust/src/main.rs`
- try coding,  auto complete (ctrl space) works, error markers works

**Comment by sunix** [comment]
@ericwill I thought filling `che-theia-plugins.yaml` would generate the files in `v3/plugins` but it doesn't?

**Comment by benoitf** [comment]
@sunix  when I'll merge https://github.com/eclipse/che-plugin-registry/pull/721 (I'm doing some final checks)

**Review by ericwill — APPROVED** [review]

**Pull request merged**
