### PR TITLE
16183 update python plugin

### PR DESCRIPTION
**Pull request by tsmaeder**
### What does this PR do?

Updates python plugin to 2020.7.94776 and the sidecar image to python 3.8.6. 2020.7.94776 is the earliest version where the debugger currently works and seems to be more functional than the latest tag.

### Fixes Issue
https://github.com/eclipse/che/issues/16183

This PR needs to be merged together with the other related PR's:

related PRs: 
* https://github.com/eclipse/che-devfile-registry/pull/294
* https://github.com/eclipse/che-plugin-registry/pull/641
* https://github.com/che-samples/django-realworld-example-app/pull/1

### CODE REVIEW

**Comment by ericwill** [comment]
`che-python-3.8` is merged and nightly builds are available: https://quay.io/repository/eclipse/che-python-3.8?tab=tags

**Comment by ericwill** [comment]
Please update the [vscode-extensions.json entry](https://github.com/eclipse/che-plugin-registry/blob/master/vscode-extensions.json#L198) for this update. 

Fields that need updating:
* `revision` "2020.7.94776"
* `sidecar -> image` "quay.io/eclipse/che-sidecar-python:3.8.6-5913fc2"
* `sidecar -> source -> revision` remove this entry as the image is built on master now, so it's no longer needed

**Review by svor — APPROVED** [review]

**Comment by ericwill** [comment]
`vscode-extensions.json field validation` seems a bit flaky these days, I'll have to look into that.

**Review by ericwill — APPROVED** [review]
PR check seems to failing for unrelated reasons. LGTM.

**Pull request merged**
