### PR TITLE
[Helm deployments] Enable TLS on the ingress.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Appends `tls:` object to the ingress if the secret name was specified.

### CODE REVIEW

**Comment by monaka** [comment]
@l0rd @sleshchenko Can I merge by myself this?

**Comment by sleshchenko** [comment]
@monaka I think it is better to get at least one approve even for small changes

**Comment by monaka** [comment]
@sleshchenko Thank you for your review.

And I agree with your opinion.
So I think it's better to be set more strict merge gate here same as `eclipse/che` repository. https://help.github.com/en/articles/enabling-required-reviews-for-pull-requests
(But I have no permission to set it..)

**Comment by sleshchenko** [comment]
@monaka I think webmaster can do it of someone creates the corresponding issue https://bugs.eclipse.org. Could you register this task?

**Comment by monaka** [comment]
@sleshchenko I see. Thanks for your suggest. I'll send the request there.

**Pull request merged**
