### PR TITLE
Adds Dependency Analytics Plugin v3

### PR DESCRIPTION
**Pull request by invincibleJai**
### What does this PR do?

Adds meta information for [Dependency Analytics](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics) Che Plugin v0.0.12/latest

What issues does this PR fix or reference?

https://github.com/redhat-developer/rh-che/issues/1045

### Dependent PR : 
- https://github.com/eclipse/che-theia/pull/297

### CODE REVIEW

**Comment by ibuziuk** [comment]
@invincibleJai have you tried the extention? does it work as expected against  `eclipse/che-remote-plugin-runner-java8:next` ?

**Comment by invincibleJai** [comment]
@ibuziuk i didn't try with `eclipse/che-remote-plugin-runner-java8:next` but it won't work for maven projects as `mvn` is  not in path i checked with exec in image.

**Comment by ibuziuk** [comment]
> i didn't try with eclipse/che-remote-plugin-runner-java8:next

hmm, but this is the container image you are referring to

**Comment by invincibleJai** [comment]
@ibuziuk Thanks for the help , `Stack analyses` i verified it's not working as `mvn not found`. LS works fine. We need a image :|

**Comment by ibuziuk** [comment]
@invincibleJai looks like you need to create an maintain a dockerimage with all required binaries (node, npm, mvn etc) for now that will be used as a sidecar for the `dependency-analytics` plugin.

**Comment by invincibleJai** [comment]
@ibuziuk ah okay, so do I need to file PR at https://github.com/eclipse/che-theia/tree/master/dockerfiles with Analytics specific Dockerfire?

**Comment by invincibleJai** [comment]
@ibuziuk have provided PR https://github.com/eclipse/che-theia/pull/297 with dockerfile, need to update this PR with correct image name once https://github.com/eclipse/che-theia/pull/297 is good to go.

**Comment by svor** [comment]
@invincibleJai Please signeoff your commit. I think 512Mi for memory limit will be enough. WDYT?

**Comment by invincibleJai** [comment]
@ibuziuk I verified it and works as expected, PTAL. Images are available now https://github.com/eclipse/che-theia/pull/297 is merged

**Comment by ibuziuk** [comment]
@l0rd @skabashnyuk @rhopp @vparfonov review of one of the code owners is required to get this PR merged

**Comment by l0rd** [comment]
@ibuziuk that's not included in the `7.0.0` endgame and the related Theia PR is not in the `7.0.0` branch. I would rather wait for `7.1.0` but can we release Che 7 on che.osio without this?

**Comment by ibuziuk** [comment]
> can we release Che 7 on che.osio

@l0rd yes, this would be just a missing feature that we would need in the subsequent releases (similar to telemetry / woopra support)

**Pull request merged**
