### PR TITLE
[WIP] Add vscode-tekton to the plugin registry

### PR DESCRIPTION
**Pull request by ericwill**
WIP as the sidecar container has not been finished -- I am using my own quay repo for testing.

Closes eclipse/che#15752

Signed-off-by: Eric Williams <ericwill@redhat.com>

### CODE REVIEW

**Comment by ericwill** [comment]
Sidecar image work is ongoing here: https://github.com/che-dockerfiles/che-sidecar-tekton/pull/2

**Comment by ericwill** [comment]
Testing on hosted Che I can see the plugin initialize, but it shows a message `Please install the OpenShift Pipelines Operator`.

**Comment by sunix** [comment]
would it be possible to also include the tekton ext to the openshift plugin ? so if you install openshift 4.4, user would have Openshift pipeline and it would make sense to have it by default.

**Comment by gattytto** [comment]
> would it be possible to also include the tekton ext to the openshift plugin ? so if you install openshift 4.4, user would have Openshift pipeline and it would make sense to have it by default.

yes you would need to add TKN binary to the openshift sidecar and maybe some more steps, I found this about TKN binary running pipeline in openshift 4.3 https://ibm-cloud-architecture.github.io/cloudpak-for-applications/liberty/liberty-deploy-tekton/

**Comment by ericwill** [comment]
Superceded by #503

**Pull request closed without merging**
