### PR TITLE
feat(plugins): Use meta.yaml content generated by script

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
- Use icons specified inside the vsix files
- Also update field information based on data from the linked vsix

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17029

### How to test this PR?
build the registry and browse plug-in registy

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

Change-Id: I6ee177116b327d479ad3ea8808ebbfb3251300e6
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by ericwill — COMMENTED** [review]
Are we in the clear from a licensing perspective?

**Comment by benoitf** [comment]
I would say yes as these icons are provided to be exposed by a registry/marketplace/etc.
These icons are already provided by open-vsx as well

**Comment by ericwill** [comment]
> I would say yes as these icons are provided to be exposed by a registry/marketplace/etc.
> These icons are already provided by open-vsx as well

OK, I agree

**Comment by vitaliy-guliy** [comment]
Why is it better to have the icons inside our repository? Why not to download them from their origins as it was before?
I'm just wonder how it's related to generating of meta.yamls

It there a script used to fetch those icons from .vsix files?

**Comment by benoitf** [comment]
@vitaliy-guliy: all that you're saying is correct
here it's like the last intermediate step before removing all meta.yaml and images and make it only available in the final image (build time fetch)

**Comment by benoitf** [comment]
closing as it was to check diff between what is generated and what is available

PR to follow is https://github.com/eclipse/che-plugin-registry/pull/721

**Pull request closed without merging**
