### PR TITLE
feat(java-plugins): update vscode-java and vscode-java-test for all java11 related plugins

### PR DESCRIPTION
**Pull request by sunix**
### What does this PR do?
Update vscode-java (jdt-ls) and vscode-java-test to the latest.

### Screenshot/screencast of this PR
Selection_279

### What issues does this PR fix or reference?
Fix https://github.com/eclipse/che/issues/19099

### How to test this PR?
This is a devfile using java plugin from the updated registry. Make sure Java feature all works fine, as well as unit tests.
```yaml
apiVersion: 1.0.0
metadata:
  generateName: test-java-extension-update-
attributes:
  multiRoot: 'on'
projects:
  - name: java-web-spring
    source:
      location: 'https://github.com/spring-projects/spring-petclinic.git'
      type: git
      commitId: 4953f87917b449a404a7f1f4e2457836b9eafbbc
  - name: event-publisher
    source:
      location: 'https://github.com/parisjug/event-publisher'
      type: git
components:
  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    registryUrl: 'https://sunix-plugin-registry-update-java-gbjp9.surge.sh/v3'
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: 8080-tcp
        port: 8080
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 768Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    image: 'quay.io/eclipse/che-java11-maven:nightly'
    alias: tools
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: JAVA_OPTS
      - value: $(JAVA_OPTS)
        name: MAVEN_OPTS
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/java-web-spring'
        type: exec
        command: mvn clean install
        component: tools
  - name: run webapp
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/java-web-spring'
        type: exec
        command: |
          java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 \
          target/*.jar
        component: tools
  - name: Debug remote java application
    actions:
      - referenceContent: |
          {
          "version": "0.2.0",
          "configurations": [
            {
              "type": "java",
              "name": "Debug (Attach) - Remote",
              "request": "attach",
              "hostName": "localhost",
              "port": 5005
            }]
          }
        type: vscode-launch

```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by benoitf** [comment]
Hello, it looks like it's missing updates on `revision` fields

**Comment by sunix** [comment]
> Hello, it looks like it's missing updates on `revision` fields

@benoitf should be fixed

**Review by ericwill — APPROVED** [review]
LGTM :+1:  but looks like GitHub actions are stalled again

**Comment by sunix** [comment]
Merging as there is no shell script changes in that PR

**Pull request merged**
