### PR TITLE
Updated smoke test curl URL which was broken.

### PR DESCRIPTION
**Pull request by karstengresch**
### What does this PR do?

Changes the documentation. It's a bit frustrating perhaps when the first curl URL example isn't working ;)

### CODE REVIEW

**Comment by skabashnyuk** [comment]
@karstengresch can you please sign https://www.eclipse.org/legal/ECA.php.  I can't merge this pr without ip-validation check.

**Comment by karstengresch** [comment]
> @karstengresch can you please sign https://www.eclipse.org/legal/ECA.php. I can't merge this pr without ip-validation check.

Thanks @skabashnyuk for the hint... Actually I've already signed it but my e-mail address at Eclipse differs from the Git Hub web based commit e-mail address which is obfuscated. I'm rather unsure about what to do now...??? Create a new account at Eclipse w/ the fake GH address or reveal the commit address and get spammed?

**Comment by slemeur** [comment]
Hi @karstengresch.
First, let me thank you for your pull request! We are always glad when people are helping especially on docs which also helps other to leverage the project.

You'll need your commit to be signed-off. You would need rework your commit in order to sign-off it. When you commit, you should do a signed off commit by using the following command:

* `git commit -s`
* or `git commit --signoff`
* or add `Signed-off-by: Your Name <your.email@example.com>` at the last line of your commit message (separated with a blank line from your commit body)

(Now that you pushed the changes to your branch, you would need to rework the branch history - if it's simpler, you can open another PR ;) )

Hope this helps.

**Comment by sleshchenko** [comment]
There is another PR that solved this bug https://github.com/eclipse/che-plugin-registry/pull/93/files
BTW Thanks for raising this issue!

**Pull request closed without merging**
