### PR TITLE
Delete deprecated Theia editor plugin version

### PR DESCRIPTION
**Pull request by mmorhun**
### What does this PR do?
This PR deletes deprecated Theia editor of `master` version.
This will help to avoid confusion between Theia editor versions.
Instead of deleted `master` version, Theia with version `next` should be used.

### CODE REVIEW

**Comment by ibuziuk** [comment]
Please be careful and do not update prod due to https://github.com/redhat-developer/rh-che/issues/1379

**Comment by benoitf** [comment]
@ibuziuk it should be good to remove master

it will let : `latest` and `next`

**Comment by garagatyi** [comment]
@ibuziuk won't it break Che 7 workspaces on prod-preview, will it? I assume prod-preview is updated on each commit

**Comment by ibuziuk** [comment]
@garagatyi sure what I mean is that this PR should not be merged until relevant changes are done in the rh-che

**Comment by garagatyi** [comment]
Please note that I added CircleCI and Eclipse sign off check to required checks for PRs.
Since this PR was created before CircleCI was configured in the repository you have to commit something to this PR to initiate CircleCI build that is required to proceed with merging the PR.
Sorry for the inconvenience.

**Comment by ibuziuk** [comment]
@mmorhun I believe https://github.com/eclipse/che-plugin-registry/blob/master/v2/plugins/eclipse/che-theia/master/meta.yaml should be also removed now

**Comment by mmorhun** [comment]
@ibuziuk thanks, I've updated PR. But that's kinda surprise, because when I created it, `v2` directory didn't exist.

**Pull request merged**
