### PR TITLE
18292 - switch to use quay copies of...

### PR DESCRIPTION
**Pull request by nickboldt**
18292 - switch to use quay copies of docker.io images

Change-Id: I3a711926c1c420eeaa4add06265cb3fb4bb294db
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
Questions:

a) is it OK to use a `latest` tag?

```
- image: "quay.io/windupeng/mta-vscode-extension:latest"
```

b) Why do we have 3 versions of code-server? Can we trash the older ones and just keep next? Or even better, should we move up to 3.7.1 and start having *released* versions in ther instead of a nightly/next/latest?

**Comment by ericwill** [comment]
> Questions:
> 
> a) is it OK to use a `latest` tag?
> 
> ```
> - image: "quay.io/windupeng/mta-vscode-extension:latest"
> ```

For a community contribution it's okay with me. There is actually a [PR](https://github.com/eclipse/che-plugin-registry/pull/701) open right now to update this plugin, and there may be a PR coming to integrate the sidecar into this repo (meaning no latest tags, `VERSION` + SHA1 tagging system).

> b) Why do we have 3 versions of code-server? Can we trash the older ones and just keep next? Or even better, should we move up to 3.7.1 and start having _released_ versions in ther instead of a nightly/next/latest?

Keep the latest version (`3.6.2`) and the others (including `next`) can be removed.

**Review by ericwill — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
I'm -1 on these changes
Plugins are coming from contributors so there is no need to fork

Also for some of them we can fix it at publishing source

Please revert, agreement was only for the images bootstraping che

**Comment by benoitf** [comment]
but if you log-in, then pull would work then you don't need that

**Comment by benoitf** [comment]
@nickboldt please revert, remove these editor images from quay.io/ecliose and drop this commit from 7.22.x branch
I asked the revert yesterday

**Comment by benoitf** [comment]
or I'll remove the image myself as https://github.com/eclipse/che-release/pull/9 is not approved

**Comment by nickboldt** [comment]
partially reverted as #706, then https://github.com/eclipse/che-release/pull/9 merged with approval.

**Pull request merged**
