### PR TITLE
Add a quarkus-java11 plugin

### PR DESCRIPTION
**Pull request by ericwill**
Add a new plugin for quarkus running on Java 11.

Fixes eclipse/che#16790

Signed-off-by: Eric Williams <ericwill@redhat.com>

### CODE REVIEW

**Comment by sunix** [comment]
Tested it but ...
```
Press F5 or click here to try again in debug mode. Download logs
Error: Failed to start the workspace: "Plugin specified by reference URL 'xyz' have missing required field 'publisher'."
```

**Comment by sunix** [comment]
looks ok to me.
I tried the plugin and it works.
However, not sure it is related or not:
- it took ages to activate the java extension
- I have some weird error in the log:

image

**Comment by ericwill** [comment]
> looks ok to me.
> I tried the plugin and it works.
> However, not sure it is related or not:
> 
>     * it took ages to activate the java extension
> 
>     * I have some weird error in the log:
> 
> 
> image

Does it happen with the Java 8 version or is it something new?

**Comment by ericwill** [comment]
[ci-test-happy-path]

**Comment by rhopp** [comment]
@ericwill Don't bother with the "happy path test" right now... It's not finished yet, but there is no way how to create the job, but enable it just for a specific PR until it's ready ;-)

**Comment by sunix** [comment]
> Does it happen with the Java 8 version or is it something new?

- I tried again and activation is better today ... (maybe network issue yesterday)
- For the error, no, but I think this is Java11 specific (JShell is not in java8 afaik from java9)

**Comment by ericwill** [comment]
> @ericwill Don't bother with the "happy path test" right now... It's not finished yet, but there is no way how to create the job, but enable it just for a specific PR until it's ready ;-)

Sorry, forgot we are in the plugin-registry!

> > Does it happen with the Java 8 version or is it something new?
> 
>     * I tried again and activation is better today ... (maybe network issue yesterday)
> 
>     * For the error, no, but I think this is Java11 specific (JShell is not in java8 afaik from java9)

I am wondering if it happens specifically with Quarkus on Java 11 or with a plain Java 11 workspace as well.

**Comment by ericwill** [comment]
I tried it out using the `che-quarkus:nightly` base image, as well as my changes and I didn't see any console log like you did @sunix, but I did see the following warnings:

quarkus-java11

**Comment by sunix** [comment]
@ericwill I just tested with that devfile: https://github.com/sunix/code-quarkus-devfile/blob/master/quarkus-java11.devfile.yaml
I don't have the previous error anymore.
The devfile is using a quarkus project where java compiler is set to 11. I think we are ready to handle the quarkus sample move to Java 11.

**Pull request merged**
