### PR TITLE
Add support for publishing multiple versions of the same plugin

### LINKED ISSUE #31: Registry doesn't support plugins with several versions
When some plugin or editor has 2 versions in registry index build check fails

<details>

```
Sending build context to Docker daemon  267.8kB
Step 1/10 : FROM mikefarah/yq
 ---> 28dd2998f056
Step 2/10 : RUN apk add --no-cache bash
 ---> Using cache
 ---> e2017954fdbb
Step 3/10 : COPY /plugins /test/plugins
 ---> Using cache
 ---> 45991a42fa51
Step 4/10 : COPY check_plugins_location.sh /test/check_plugins_location.sh
 ---> 32c202c5fcdc
Step 5/10 : RUN cd /test/ && ./check_plugins_location.sh
 ---> Running in 1370d8fd82dc
./check_plugins_location.sh: line 18: cd: too many arguments
11:32:04 main [ERRO] open meta.yaml: no such file or directory
!!! ID mismatch in plugin 'org.eclipse.che.editor.theia/1.0.0/
!!!   id in meta.yaml: 'Error: open meta.yaml: no such file or directory
Usage:
  yq read [yaml_file] [path] [flags]

Aliases:
  read, r

Examples:

yq read things.yaml a.b.c
yq r - a.b.c (reads from stdin)
yq r things.yaml a.*.c
yq r -d1 things.yaml a.array[0].blah
yq r things.yaml a.array[*].blah
      

Flags:
  -d, --doc string   process document index number (0 based, * for all documents) (default "0")
  -h, --help         help for read
  -j, --tojson       output as json

Global Flags:
  -t, --trim      trim yaml output (default true)
  -v, --verbose   verbose mode'
!!!   id directory name: 'org.eclipse.che.editor.theia' 
11:32:04 main [ERRO] open meta.yaml: no such file or directory
!!! Version mismatch in plugin 'org.eclipse.che.editor.theia/1.0.0/
1.0.1':
!!!   version in meta.yaml: 'Error: open meta.yaml: no such file or directory
Usage:
  yq read [yaml_file] [path] [flags]

Aliases:
  read, r

Examples:

yq read things.yaml a.b.c
yq r - a.b.c (reads from stdin)
yq r things.yaml a.*.c
yq r -d1 things.yaml a.array[0].blah
yq r things.yaml a.array[*].blah
      

Flags:
  -d, --doc string   process document index number (0 based, * for all documents) (default "0")
  -h, --help         help for read
  -j, --tojson       output as json

Global Flags:
  -t, --trim      trim yaml output (default true)
  -v, --verbose   verbose mode'
!!!   version directory name: '1.0.0/
1.0.1' 
The command '/bin/sh -c cd /test/ && ./check_plugins_location.sh' returned a non-zero code: 1
```
</details>

### PR DESCRIPTION
**Pull request by l0rd**
### What does this PR do?

Fixes #31

### CODE REVIEW

**Comment by skabashnyuk** [comment]
What is the difference with https://github.com/eclipse/che-plugin-registry/pull/32 ?
@garagatyi @l0rd looks like you are fixing the same issue. what pr would you like to use as major?

**Comment by garagatyi** [comment]
@l0rd yeah, I provided the same fix on Friday. And since it was approved I've just merged it.

**Comment by l0rd** [comment]
2 PRs are better than one 😅 Haven't saw the other one but I did the change
locally on Thursday to test anew version  of Theia.

**Comment by garagatyi** [comment]
@l0rd I also implemented that just to test my own stuff :)

**Pull request closed without merging**
