### PR TITLE
feat(alpine): Change parent image to be alpine based as well

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

It replaces centos/httpd with alpine/httpd allowing to be smaller/updated and also multi-arch

Change-Id: I7a3050fcfdea30fe08e4127cf581713a9cc91b85
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by rhopp** [comment]
@benoitf Is it possible this PR could have broken plugin registry? Our nightly tests failed on plugin registry not being able to start.
This is log output of plugin-registry pod:
<details>
<summary>plugin-registry.log</summary>

```
Checking meta /var/www/html/v3/plugins/bitlang/cobol/5.0.6/meta.yaml
Checking meta /var/www/html/v3/plugins/bitlang/cobol/6.0.19/meta.yaml
Checking meta /var/www/html/v3/plugins/bitlang/cobol/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/cobol-language-support/0.10.1/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/cobol-language-support/0.8.3/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/cobol-language-support/0.9.1/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/cobol-language-support/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/debugger-for-mainframe/1.0.0/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/debugger-for-mainframe/1.0.2/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/debugger-for-mainframe/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/explorer-for-endevor/0.9.0/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/explorer-for-endevor/0.9.1/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/explorer-for-endevor/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/hlasm-language-support/0.8.1/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/hlasm-language-support/0.9.1/meta.yaml
Checking meta /var/www/html/v3/plugins/broadcommfd/hlasm-language-support/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/camel-tooling/vscode-apache-camel/0.0.14/meta.yaml
Checking meta /var/www/html/v3/plugins/camel-tooling/vscode-apache-camel/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/cdr/code-server/2.1523-vsc1.38.1/meta.yaml
Checking meta /var/www/html/v3/plugins/cdr/code-server/2.1650-vsc1.39.2/meta.yaml
Checking meta /var/www/html/v3/plugins/cdr/code-server/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/cdr/code-server/next/meta.yaml
Checking meta /var/www/html/v3/plugins/che-incubator/cpptools/0.1/meta.yaml
Checking meta /var/www/html/v3/plugins/che-incubator/cpptools/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/che-incubator/theia-dev/0.0.1/meta.yaml
Checking meta /var/www/html/v3/plugins/che-incubator/theia-dev/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/che-incubator/typescript/1.30.2/meta.yaml
Checking meta /var/www/html/v3/plugins/che-incubator/typescript/1.35.1/meta.yaml
Checking meta /var/www/html/v3/plugins/che-incubator/typescript/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/dirigiblelabs/dirigible/3.4.0/meta.yaml
Checking meta /var/www/html/v3/plugins/dirigiblelabs/dirigible/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/0.0.1/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.0.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.1.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.10.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.11.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.2.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.3.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.3.1/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.3.2/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.3.3/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.4.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.5.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.5.1/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.6.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.7.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.7.1/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.8.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.9.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.9.1/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/7.9.2/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-machine-exec-plugin/nightly/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.0.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.0.0-next/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.0.0-rc-3.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.0.0-rc-4.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.1.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.10.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.11.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.2.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.3.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.3.1/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.3.2/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.3.3/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.4.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.5.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.5.1/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.6.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.7.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.7.1/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.8.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.9.0/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.9.1/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/7.9.2/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/che-theia/next/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/cloud-shell/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/eclipse/cloud-shell/nightly/meta.yaml
Checking meta /var/www/html/v3/plugins/joaompinto/vscode-asciidoctor/2.7.6/meta.yaml
Checking meta /var/www/html/v3/plugins/joaompinto/vscode-asciidoctor/2.7.7/meta.yaml
Checking meta /var/www/html/v3/plugins/joaompinto/vscode-asciidoctor/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/lfs/vscode-emacs-friendly/0.9.0/meta.yaml
Checking meta /var/www/html/v3/plugins/lfs/vscode-emacs-friendly/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/microshed/mp-starter-vscode-ext/0.2.0/meta.yaml
Checking meta /var/www/html/v3/plugins/microshed/mp-starter-vscode-ext/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/0.1.17/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.0/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.4/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.0.9/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.1.0/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-python/python/2019.2.5558/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-python/python/2019.3.6558/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-python/python/2019.5.18875/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-python/python/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-vscode/go/0.11.0/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-vscode/go/0.11.4/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-vscode/go/0.9.2/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-vscode/go/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-vscode/node-debug2/1.33.0/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-vscode/node-debug2/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-vscode/vscode-github-pullrequest/0.8.0/meta.yaml
Checking meta /var/www/html/v3/plugins/ms-vscode/vscode-github-pullrequest/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/pizzafactory/vscode-libra-move/0.0.10/meta.yaml
Checking meta /var/www/html/v3/plugins/pizzafactory/vscode-libra-move/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/pizzafactory/xtend-lang/0.1.0/meta.yaml
Checking meta /var/www/html/v3/plugins/pizzafactory/xtend-lang/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/pizzafactory/xtext-lang/0.4.0/meta.yaml
Checking meta /var/www/html/v3/plugins/pizzafactory/xtext-lang/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/dependency-analytics/0.0.12/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/dependency-analytics/0.0.13/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/dependency-analytics/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java/0.38.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java/0.43.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java/0.45.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java/0.46.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java/0.50.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java/0.55.1/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java/0.57.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java11/0.46.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java11/0.50.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java11/0.55.1/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java11/0.57.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java11/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java8/0.46.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java8/0.50.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java8/0.55.1/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java8/0.57.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/java8/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/php/1.0.13/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/php/1.0.14/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/php/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/php-debugger/1.13.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/php-debugger/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/project-initializer/0.0.10/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/project-initializer/0.0.9/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/project-initializer/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/quarkus-java8/1.2.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/quarkus-java8/1.2.0a/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/quarkus-java8/1.2.0b/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/quarkus-java8/1.3.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/quarkus-java8/1.3.0a/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/quarkus-java8/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/rhamt/0.0.11/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/rhamt/0.0.23/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/rhamt/0.0.8/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/rhamt/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-apache-camel/0.0.16/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-apache-camel/0.0.18/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-apache-camel/0.0.20/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-apache-camel/0.0.22/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-apache-camel/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-camelk/0.0.10/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-camelk/0.0.10-4/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-camelk/0.0.11/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-camelk/0.0.12/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-camelk/0.0.13/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-camelk/0.0.9/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-camelk/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-openshift-connector/0.0.17/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-openshift-connector/0.0.19/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-openshift-connector/0.0.21/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-openshift-connector/0.1.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-openshift-connector/0.1.1/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-openshift-connector/0.1.2/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-openshift-connector/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-wsdl2rest/0.0.11/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-wsdl2rest/0.0.9/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-wsdl2rest/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-xml/0.10.1/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-xml/0.3.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-xml/0.5.1/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-xml/0.7.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-xml/0.9.1/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-xml/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-yaml/0.3.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-yaml/0.4.0/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat/vscode-yaml/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.1/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.2/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.4/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.5/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat-developer/che-omnisharp-plugin/0.0.6/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat-developer/che-omnisharp-plugin/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat-developer/netcoredbg-theia-plugin/0.0.1/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat-developer/netcoredbg-theia-plugin/0.0.3/meta.yaml
Checking meta /var/www/html/v3/plugins/redhat-developer/netcoredbg-theia-plugin/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/sonarsource/sonarlint-vscode/0.0.1/meta.yaml
Checking meta /var/www/html/v3/plugins/sonarsource/sonarlint-vscode/0.0.2/meta.yaml
Checking meta /var/www/html/v3/plugins/sonarsource/sonarlint-vscode/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/testthedocs/vale/0.9.1/meta.yaml
Checking meta /var/www/html/v3/plugins/testthedocs/vale/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/vscodevim/vim/1.11.3/meta.yaml
Checking meta /var/www/html/v3/plugins/vscodevim/vim/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/ws-skeleton/eclipseide/4.9.0/meta.yaml
Checking meta /var/www/html/v3/plugins/ws-skeleton/eclipseide/latest/meta.yaml
Checking meta /var/www/html/v3/plugins/ws-skeleton/jupyter/5.7.0/meta.yaml
Checking meta /var/www/html/v3/plugins/ws-skeleton/jupyter/latest/meta.yaml
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.10. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.10. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 15 06:16:48.122262 2020] [mpm_event:notice] [pid 1:tid 139861858659656] AH00489: Apache/2.4.43 (Unix) configured -- resuming normal operations
[Wed Apr 15 06:16:48.122326 2020] [core:notice] [pid 1:tid 139861858659656] AH00094: Command line: 'httpd -D FOREGROUND'
```
</details>

**Comment by sparkoo** [comment]
@rhopp @benoitf failed same for me, I've reported https://github.com/eclipse/che/issues/16605

**Comment by benoitf** [comment]
@rhopp well maybe I didn't wanted to merge early without asking QE but it has been merged

the output log looks fine

**Comment by benoitf** [comment]
@sparkoo / @rhopp using minikube, CRC or other config ? I can do revert for now

**Comment by sparkoo** [comment]
@benoitf minikube for me, see the reported issue https://github.com/eclipse/che/issues/16605

**Pull request merged**
