### PR TITLE
Fix image version to the 7.0.0-rc-3.0

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### What does this PR do?

Fix image version to the 7.0.0-rc-3.0

### CODE REVIEW

**Comment by benoitf** [comment]
hello, I'm not sure that it's the expected behaviour. 

If it expected then I don't see why we have different repositories / lifecycles / plug-ins

**Comment by benoitf** [comment]
from what i've understood, :next of endpoints image needs to be tagged with the associated che-theia image but the plug-in version can stay the same

After it's tagged, then version are backed to :next 

ppl deploying the registry 7.0.0-RC3 will then have theia endpoint images of 7.0.0-RC3 

so no need to change stacks etc for each che version

**Comment by vparfonov** [comment]
so i mean in meta.yaml always will be latest version like here? 
https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/ms-python/python/latest/meta.yaml#L4

**Comment by benoitf** [comment]
The registry is already per che version, so no need to change plugin's versions. Just the image used by plug-ins

**Pull request closed without merging**
