### PR TITLE
Release Che 7.0.0 rc 4.0

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### What does this PR do?

TODO

### CODE REVIEW

**Comment by l0rd** [comment]
@vparfonov can you Target branch 7.0.0-rc-4.0 instead of targeting master

**Comment by vparfonov** [comment]
> I am on my mobile and it's hard to check: does the meta.yaml in che-theia/latest have the same endpoints as the one in che-theia/7.0.0-rc4?

In "latest" it set to the eclipse/che-theia:latest

**Comment by l0rd** [comment]
> > I am on my mobile and it's hard to check: does the meta.yaml in che-theia/latest have the same endpoints as the one in che-theia/7.0.0-rc4?
> 
> In "latest" it set to the eclipse/che-theia:latest,
> https://github.com/eclipse/che-theia/pull/370/files

Yes I saw that. But the meta.yaml of latest and 7.0.0-rc4 should be identical (except for the tag of course)

**Comment by vparfonov** [comment]
> > > I am on my mobile and it's hard to check: does the meta.yaml in che-theia/latest have the same endpoints as the one in che-theia/7.0.0-rc4?
> > 
> > 
> > In "latest" it set to the eclipse/che-theia:latest,
> > https://github.com/eclipse/che-theia/pull/370/files
> 
> Yes I saw that. But the meta.yaml of latest and 7.0.0-rc4 should be identical (except for the tag of course)

Got it and fix

**Comment by l0rd** [comment]
Nice thanks @vparfonov

**Pull request merged**
