### PR TITLE
Use new version of che-sidecar-go image

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Uses `che-sidecar-go:1.14.4` image in `golang/go` plugin.

Devfile to test
```

apiVersion: 1.0.0
metadata:
  generateName: golang-
projects:
-
  name: example
  source:
    type: git
    location: https://github.com/golang/example.git
  clonePath: src/github.com/golang/example/
components:
-
  type: chePlugin
  reference: >-
    https://raw.githubusercontent.com/vitaliy-guliy/che-plugin-registry/update-go-0.14.4/v3/plugins/golang/go/0.14.4/meta.yaml
  alias: go-plugin
-
  type: dockerimage
  # this version is used in the plugin
  image: quay.io/eclipse/che-golang-1.12:nightly
  alias: go-cli
  env:
    - name: GOPATH
      # replicate the GOPATH from the plugin
      value: /go:$(CHE_PROJECTS_ROOT)
    - name: GOCACHE
      # replicate the GOCACHE from the plugin, even though the cache is not shared
      # between the two
      value: /tmp/.cache
  endpoints:
    - name: '8080/tcp'
      port: 8080
  memoryLimit: 512Mi
  mountSources: true
commands:
-
  name: run outyet
  actions:
  - type: exec
    component: go-cli
    command: go get -d && go run main.go
    workdir: ${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet
-
  name: stop outyet
  actions:
  - type: exec
    component: go-cli
    command: kill $(pidof go)
-
  name: test outyet
  actions:
  - type: exec
    component: go-cli
    command: go test
    workdir: ${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet
-
  name: run current file
  actions:
  - type: exec
    component: go-cli
    command: go get -d && go run ${file}
    workdir: ${fileDirname}
-
  name: Debug current file
  actions:
  - type: vscode-launch
    referenceContent: |
      {
        "version": "0.2.0",
        "configurations": [
          {
            "name": "Debug current file",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}"
          }
        ]
      }

```

### CODE REVIEW

**Comment by benoitf** [comment]
FYI I have

```
Extension-Host:PLUGIN_HOST(49): PluginManagerExtImpl/loadPlugin(/default-theia-plugins/vscode-builtin-configuration-editing/extension/dist/extension)
Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
Extension-Host:Child process git stderr: Cloning into '/projects/src/github.com/golang/example'...
```

Errors on the `hosted-instance.log` output


And I have to click on "use gopls language server" and then "reload my window" to have working code completion.

**Comment by vitaliy-guliy** [comment]
> FYI I have
> 
> ```
> Extension-Host:PLUGIN_HOST(49): PluginManagerExtImpl/loadPlugin(/default-theia-plugins/vscode-builtin-configuration-editing/extension/dist/extension)
> Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
> Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
> Extension-Host:Child process git stderr: Cloning into '/projects/src/github.com/golang/example'...
> ```
> 
> Errors on the `hosted-instance.log` output
> 
> And I have to click on "use/update gopls language server" and then "reload my window" to have working code completion.

Today I got the same.
But after removing the workspace and creating it again everything was fine.
Will check it again..

**Comment by benoitf** [comment]
@vitaliy-guliy I think I saw @tsmaeder saying it should be `tasks` and not `configurations` but then I don't know how may devfiles are invalid ?

**Comment by vitaliy-guliy** [comment]
> FYI I have
> 
> ```
> Extension-Host:PLUGIN_HOST(49): PluginManagerExtImpl/loadPlugin(/default-theia-plugins/vscode-builtin-configuration-editing/extension/dist/extension)
> Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
> Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
> Extension-Host:Child process git stderr: Cloning into '/projects/src/github.com/golang/example'...
> ```
> 
> Errors on the `hosted-instance.log` output
> 
> And I have to click on "use/update gopls language server" and then "reload my window" to have working code completion.

There is the same output in a workspace without Go plugin
```
Extension-Host:PLUGIN_HOST(48): PluginManagerExtImpl/loadPlugin(/default-theia-plugins/vscode-builtin-configuration-editing/extension/dist/extension)
Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
Extension-Host:Error parsing configurations: error: 4, length:  0, offset:  0
Extension-Host:Child process git stderr: Cloning into '/projects/src/github.com/golang/example'...
```
So, it's not related to the Go.

**Pull request merged**
