### PR TITLE
fix: corrects article in desc of code-server

### PR DESCRIPTION
**Pull request by bartoszmajsak**
### What does this PR do?

Corrects an article in the description of code-server plugin

### CODE REVIEW

**Comment by ericwill** [comment]
Hi - I'd like to merge this but it looks like you need to sign your commit, so the ECA check can happen.

**Comment by bartoszmajsak** [comment]
> Hi - I'd like to merge this but it looks like you need to sign your commit, so the ECA check can happen.

I made the change through GH and thus it was signed using GH key as you can see on the screenshot:

image

Is it not enough?

**Comment by bartoszmajsak** [comment]
Ah ok, it requires singed-off footer. I will amend then.

**Comment by ericwill** [comment]
You have to close this PR and open another one.

**Comment by benoitf** [comment]
AFAIK It's ok to force push commit without opening a new PR

**Comment by ericwill** [comment]
> AFAIK It's ok to force push commit without opening a new PR

Or that. :)

**Comment by bartoszmajsak** [comment]
@ericwill done :)

**Pull request merged**
