### PR TITLE
feat(devfile): Generates devfile.yaml in addition to meta.yaml for che-editors and che-plugins

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Write devfile.yaml in addition to meta.yaml for che-plugins and che-editors

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/19060

### How to test this PR?
Look at generated results in `latest` folder for example, it should include both meta.yaml and devfile.yaml

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

Change-Id: Ibefbb93bc1eab00cdbfc1fe1e2ed2caac87166ce
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by sleshchenko — COMMENTED** [review]
LGTM

The only stuff that is missing: volumes components.
Comparing to devfile v1, volume mount is not enough, volume component should be declared explicitly, like for theia:
```yaml
components:
- name: plugins
  volume: {}
- name: theia-local
  volume: {}
- name: remote-endpoint
  volume:
    ephemeral: true
```
Then plugins will not re-declare volume but just rely on the ones from Che Theia.

**Comment by benoitf** [comment]
@sleshchenko yes thanks, Angel told me about volumes yesterday.

Is that ephemeral is supported right now ?

**Comment by sleshchenko** [comment]
From Devfile API perspective - they are supported, from DevWorkspace Operator - they will be soon https://github.com/devfile/devworkspace-operator/pull/281

**Comment by benoitf** [comment]
@sleshchenko ok but DevWorkspace Operator won't reject the file if ephemeral is used ?

**Comment by sleshchenko** [comment]
> @sleshchenko ok but DevWorkspace Operator won't reject the file if ephemeral is used ?

I tried [Angel's sample](https://github.com/amisevsk/devworkspace-operator/blob/ephemeral-volumes/samples/with-k8s-ref/emptyDir-theia.yaml) with empty dir and no error is reported, workspace is started with PVC.

**Comment by benoitf** [comment]
PR updated with volumes generation

**Review by sleshchenko — APPROVED** [review]
LGTM

maybe it also makes sense to add devfile.yaml links into index.json

**Comment by benoitf** [comment]
devfile links added

**Review by ericwill — APPROVED** [review]

**Pull request merged**
